CREATE TABLE IF NOT EXISTS `acronym_configs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `isEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `channels` TEXT NOT NULL,
  `enabledAcronyms` TEXT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
